POST  http://localhost:3000/api/v1/Instructor/signup HTTP/1.1
Content-Type: application/json

{
    
    "email": "aliDoe@outlook.com",
    "firstName": "ali",
    "lastName": "Doe",
    "password": "password",
    "phone": "+20124886711",
    "departmentId": "DEPT001"
  
}
###

POST http://localhost:3000/api/v1/school/signup HTTP/1.1
Content-Type: application/json

{
   "name": "Faculty of art",
    "phone": "+20123477789",
    "email": "art@cu.edu.eg",
    "adminPassword": "password",
    "collegeId": "COLLEGE001"
  }
###

  POST http://localhost:3000/api/v1/college/signup HTTP/1.1
  Content-Type: application/json

  {
     
    "name": "Ain Shams University",
    "email": "AinShams@email.com",
    "phone": "0123456999",
    "location": "Cairo, Egypt",
    "foundedAt": 1952,
    "adminPassword": "password"
  
  }

### 

  POST http://localhost:3000/api/v1/student/signup HTTP/1.1
  Content-Type: application/json

  {
     "email": "alaa@outlook.com",
    "firstName": "alaa",
    "lastName": "Doe",
    "password": "password",
    "phone": "+20123456119",
    "level": 3,
    "departmentId": "DEPT001"
  }
